// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs3vXDE6Kp2ShItPzOkfqHdOKWKVdkg3M',
    appId: '1:884200536012:web:84aa5072fad0bd6c7d0f69',
    messagingSenderId: '884200536012',
    projectId: 'nutimate-app',
    authDomain: 'nutimate-app.firebaseapp.com',
    storageBucket: 'nutimate-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExKgenamZiMmD29TW6lGz_IuXwS8_WKc',
    appId: '1:884200536012:android:9c012994c9d129527d0f69',
    messagingSenderId: '884200536012',
    projectId: 'nutimate-app',
    storageBucket: 'nutimate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsYaP9vQSL_qooKLb_4DK9GCtQfWVspVs',
    appId: '1:884200536012:ios:f328e844b9b1d9f77d0f69',
    messagingSenderId: '884200536012',
    projectId: 'nutimate-app',
    storageBucket: 'nutimate-app.firebasestorage.app',
    iosBundleId: 'com.example.nutrimateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsYaP9vQSL_qooKLb_4DK9GCtQfWVspVs',
    appId: '1:884200536012:ios:f328e844b9b1d9f77d0f69',
    messagingSenderId: '884200536012',
    projectId: 'nutimate-app',
    storageBucket: 'nutimate-app.firebasestorage.app',
    iosBundleId: 'com.example.nutrimateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs3vXDE6Kp2ShItPzOkfqHdOKWKVdkg3M',
    appId: '1:884200536012:web:787ed5dea2664b6a7d0f69',
    messagingSenderId: '884200536012',
    projectId: 'nutimate-app',
    authDomain: 'nutimate-app.firebaseapp.com',
    storageBucket: 'nutimate-app.firebasestorage.app',
  );
}
